from django.urls import path
from .views import (
    generate_qr_code,
    home,
    register,
    register_user,
    sign_in,
    sign_in_user,
    profile,
    wallet,
    deposit,
    start_deposit,
    process_deposit,
    submit_payment_proof,
    update_invoice_status,
    deposit_issue, 
    deposit_history,
    transactions,
    submit_deposit_issue,
    withdrawal,
    start_withdrawal,
    withdrawal_history,
    withdraw_referral_bonus,
    vip,
    upgrade_tier,
    upgrade_level,
    announcements,
    notifications,
    sign_out,
    get_broadcast_message,
    mark_as_read,
    delete_notification,
    read_notifications,
    redeem_gift,
    redeem_gift_codde,
    team_report,
    get_uid,
    get_uid_info,
    filter_by_level,
    filter_by_date,
    filter_deposits_by_date,
    filter_deposits_by_status,
    filter_withdrawal_by_date,
    filter_withdrawal_by_status,
    filter_transation_by_status,
    filter_transaction_by_date,
    profile_settings,
    change_username,
    change_login_password,
    change_password,
    reset_password,
    send_otp,
    reset_login_password,
    feedback,
    send_feedback,
    grant_gift,
    customer_service,
    change_language,
    privacy_agreement,
    risk_disclosure,
    about
)

urlpatterns = [
    path('', home, name='home'),
    path('generate_qr/', generate_qr_code, name='generate_qr_code'),
    path('grant-spin-wheel-price/', grant_gift, name='grant_gift'),
    path('register/', register, name='register'),
    path('register/<str:inv_code>/', register, name='register'),
    path('register-user/', register_user, name='register_user'),
    path('sign-in/', sign_in, name='sign_in'),
    path('sign-in-user/', sign_in_user, name='sign_in_user'),
    path('sign-out/', sign_out, name='sign_out'),
    path('profile/', profile, name='profile'),
    path('profile/feedback/', feedback, name='feedback'),
    path('profile/settings/', profile_settings, name='profile_settings'),
    path('profile/settings/login-password/', change_login_password, name='change_login_password'),
    path('wallet/', wallet, name="wallet"),
    path('wallet/withdraw-referral-bonus/', withdraw_referral_bonus, name="withdraw_referral_bonus"),
    path('wallet/deposit/', deposit, name="deposit"),
    path('wallet/deposit/update-invoice/', update_invoice_status, name="update_invoice_status"),
    path('wallet/deposit/submit-payment-proof/', submit_payment_proof, name="submit_payment_proof"),
    path('wallet/deposit/start-deposit/', start_deposit, name="start_deposit"),
    path('wallet/deposit/process-deposit/<str:transaction_id>/', process_deposit, name="process_deposit"), 
    path('wallet/transaction-history/', transactions, name="transaction_history"),
    path('wallet/deposit-history/', deposit_history, name="deposit_history"),
    path('wallet/withdrawal-history/', withdrawal_history, name="withdrawal_history"),
    path('wallet/deposit-issue', deposit_issue, name="deposit_issue"),
    path('wallet/deposit-issue/submit/', submit_deposit_issue, name="submit_deposit_issue"),
    path('wallet/withdrawal/', withdrawal, name="withdrawal"),
    path('wallet/withdrawal/start_withdrawal/', start_withdrawal, name="start_withdrawal"),
    path('change-username/', change_username, name="change_username"),
    path('change-password/', change_password, name="change_password"),
    path('vip/', vip, name='vip'),
    path('vip/upgrade/<str:level>/', upgrade_tier, name='upgrade_tier'),
    path('upgrade-level/', upgrade_level, name='upgrade_level'),
    path('announcements/', announcements, name="announcements"),
    path('notifications/', notifications, name="notifications"),
    path('read-notifications/', read_notifications, name="read_notifications"),
    path('get-broadcast-message/', get_broadcast_message, name="get_broadcast_message"),
    path('mark-as-read/', mark_as_read, name="mark_as_read"),
    path('delete-notification/', delete_notification, name="delete_notification"),
    path('redeem-gift/', redeem_gift, name='redeem_gift'),
    path('redeem-gift-codde/', redeem_gift_codde, name='redeem_gift_codde'),
    path('team-report/', team_report, name='team_report'),
    path('get-uid-info/', get_uid_info, name="get_uid_info"),
    path('get-uid/', get_uid, name="get_uid"),
    path('filter-by-level/', filter_by_level, name="filter_by_level"),
    path('filter-by-date/', filter_by_date, name="filter_by_date"),
    path('filter-transaction-by-date/', filter_transaction_by_date, name='filter_transation_by_date'),
    path('filter-transaction-by-status/', filter_transation_by_status, name='filter_transation_by_status'),
    path('filter-deposit-by-status/', filter_deposits_by_status, name='filter_deposits_by_status'),
    path('filter-deposit-by-date/', filter_deposits_by_date, name='filter_deposits_by_date'),
    path('filter-withdrawal-by-status/', filter_withdrawal_by_status, name='filter_withdrawal_by_status'),
    path('filter-withdrawal-by-date/', filter_withdrawal_by_date, name='filter_withdrawal_by_date'),
    path('reset-passwod/', reset_password, name="reset_password"),
    path('reset-passwod/send-otp/', send_otp, name="send_otp"),
    path('reset-login-password/', reset_login_password, name="reset_login_password"),
    path('customer-service/', customer_service, name='customer_service'),
    path('send-feedback/', send_feedback, name="send_feedback"),
    path('change-language/', change_language, name="change_language"),
    path('about/', about, name='about'),
    path('about/privacy-agreement/', privacy_agreement, name='privacy_agreement'),
    path('about/risk-disclosure/', risk_disclosure, name="risk_disclosure")
]